### ISSUE TITLE
Download : Angels & Airwaves Lifeforms Album Leak Zip

### ISSUE THREAD

**Issue by new-album-zip** [readthedocs/tutorial-template#1]
Download : Angels & Airwaves Lifeforms Album Leak Zip Welcome Folks To hasitmusic, Another album of that day “Lifeforms” by “Angels & Airwaves” which is scheduled to be released on September 24, 2021.The album consist of 10 tracks. But here the leaked file is available.

**[DOWNLOAD FREE ALBUM HERE](https://www.hasitmusic.com/download-angels-airwaves-lifeforms-album/)**

**[DOWNLOAD FREE ALBUM HERE](https://www.hasitmusic.com/download-angels-airwaves-lifeforms-album/)**

Tracklist :
01. Timebomb
02. Euphoria
03. Spellbound
04. No More Guns
05. Losing My Mind
06. Automatic
07. Restless Souls
08. Rebel Girl
09. A Fire In A Nameless Town
10. Kiss & Tell

**Comment by astrojuanlu** [comment]
Reported.
